version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
      - ./media:/app/media
      - ./logs:/app/logs
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-me-in-production}
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CSRF_TRUSTED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
      - PROXY_ENABLED=${PROXY_ENABLED:-False}
      - SOCKS_PROXY=${SOCKS_PROXY:-}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
