# Generated by Django 5.2.6 on 2025-09-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="media_type",
            field=models.CharField(default="movie", max_length=10),
        ),
    ]
