# Generated by Django 5.2.6 on 2025-09-07 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_movie_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrating",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
