# Generated by Django 5.2.6 on 2025-09-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_userrating_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrating",
            name="watched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
