# Generated by Django 5.2.6 on 2025-09-07 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_userrating_watched_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrating",
            name="watched_status",
        ),
    ]
