# Generated by Django 5.2.6 on 2025-09-08 06:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_remove_userrating_watched_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tmdb_api_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="TMDB API Key"
                    ),
                ),
                (
                    "trakt_username",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Trakt.tv Username"
                    ),
                ),
                (
                    "trakt_client_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Trakt.tv Client ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
