# Generated by Django 5.2.6 on 2025-10-23 14:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_importtask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="plex_webhook_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Plex Webhook Created"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="plex_webhook_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Plex Webhook Enabled"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="plex_webhook_token",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Plex Webhook Token",
            ),
        ),
        migrations.CreateModel(
            name="PlexWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="Event Type"),
                ),
                ("payload", models.JSONField(verbose_name="Payload")),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Processed"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plex Webhook Event",
                "verbose_name_plural": "Plex Webhook Events",
                "ordering": ["-created_at"],
            },
        ),
    ]
