# Generated by Django 5.2.6 on 2025-10-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_usersettings_plex_webhook_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Русский")],
                default="en",
                max_length=10,
                verbose_name="Interface Language",
            ),
        ),
    ]
