# Generated by Django 5.2.6 on 2025-10-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_usersettings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster_cached_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Poster Cache Date"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posters/",
                verbose_name="Cached Poster",
            ),
        ),
    ]
